# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26844737c00879642585c8a2be4d1d087299d91b2e3a2f15dd95053ab127b520634299baee4e3d97811a5d37e9c71af15c2bcad610bae3f43ee997b6ec08530b

test:
  secret_key_base: 55a411fab37d4032280a9d125ac982524244af2886d06840f4528601728ce1c4c9390b7dd24bfef2dbb972cb4e8dd97650e8071671deda0a0419daa86847a650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
